[package]
name = "lsc"
version = "0.0.1"
authors = ["afri 5chdn <afri@5chdn.co>"]

[dependencies]
termion = "1.3.0"

[dependencies.cursive]
version = "0.5.0"
default-features = false
features = ["termion-backend"]
